
<!-- saved from url=(0083)https://raw2.github.com/MoKee/android_frameworks_base/kk_mkt/libs/phoneloc/Makefile -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;"># Copyright (C) 2012 - 2014 The MoKee OpenSource Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
#

CC	= g++
CFLAGS	= -Wall -W -O2 -g

PROGS	= generateData
OBJS	= GenerateData.o  Global.o

all: depend $(PROGS)

.PHONY : depend
depend: $(patsubst %.o,%.cpp,$(filter %.o,$(OBJS)))
	@$(CC) -MM $(CFLAGS) -I.. $^ 1&gt; .depend


clean: 
	-rm -f *.o $(PROGS) .depend

%.o: %.cpp
	$(CC) $(CFLAGS) -c -o $*.o $&lt;

$(PROGS): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) 

ifneq ($(wildcard .depend),)
include .depend
endif
</pre></body></html>